### ISSUE TITLE
Can't make Maple Planks with Maple Logs

### ISSUE THREAD

**Issue by iShockGIT** [Yirmiri/Excessive-Building-Forge#11]
![2024-03-22_10 38 33](https://github.com/Yirmiri/Excessive-Building/assets/18996042/dc7bcf5c-fb82-454c-a3f4-e6d8606acfae)
![2024-03-22_10 38 36](https://github.com/Yirmiri/Excessive-Building/assets/18996042/7924986e-3c65-4c80-a54c-630d8b80d244)

I can't make maple planks with Maple logs. There's no legitimate way to make maple planks D:

**Comment by Yirmiri** [comment]
Can you please provide a list of your current mods, game version, and mod version.
I have checked and the recipe for logs to maple planks is working fine.

**Comment by Alaric323** [comment]
Definitely a mod interaction, in my testing with the MineColonies issue I can craft logs to planks with only Excessive Building and Minecolonies.
