### ISSUE TITLE
Rainbow Glass doesn't change beacon colors

### ISSUE THREAD

**Issue by steve-the-player** [Yirmiri/Excessive-Building-Forge#12]
<img width="1512" alt="Screenshot 2024-03-22 at 6 02 12 PM" src="https://github.com/Yirmiri/Excessive-Building/assets/61434698/e4ff0feb-9905-42f7-8371-893eb6d323ae">
I just want party beacons. 

Doesn't work with panes either

**Comment by Yirmiri** [comment]
Originally never intended to have a special rainbow color but if I have some time I can see what I can do
