### ISSUE TITLE
[1.20.1 - V2.1.3 and 2.1.4.1] Mod Breaks MineColonies Forester Sapling Menu

### ISSUE THREAD

**Issue by Alaric323** [Yirmiri/Excessive-Building-Forge#13]
Hello!  I've both Excessive Building v2.1.3 and MineColonies (1.1.515, but also affects 1.1.484 before I updated) in a modpack.  When Excessive Building is enabled, the sapling list of the Forester Hut fails to show any saplings.  Removing Excessive Building restores the list.

Functionally, this prevents the MineColonies Forester NPCs from replanting saplings after cutting down trees as you cannot tell them what saplings to replant.  

There seems to be previous issues related to saplings, perhaps this is related?  I can provide additional info if needed.

Edit: I tested 2.1.4.1 as well, same issue.  I also tested with ONLY Excessive Building and MineColonies (along with their dependents: TerraBlender, Domum Ornamentum, Structurize, and Block UI Library).  The bug still occurs.  I can provide logs with only these mods if needed, should shorten them considerably.

**Comment by Alaric323** [comment]
Some extra information, this is breaking Botania as well when trying to craft a Rune of Spring.  It appears that something from Excessive Building is overriding the ~~forge:sapling or~~ minecraft:saplings ITEM tags, causing anything that uses ~~forge:sapling~~ minecraft:saplings to break.  Block tags are set correctly, but all other saplings lose their item tags aside from forge:sapling.

Rune of Spring With Excessive Building (minecraft:saplings is now a broken tag entry):
![image](https://github.com/Yirmiri/Excessive-Building/assets/4038592/7403b75a-0c35-41a9-a319-4429ae3bc230)

Rune of Spring Without Excessive Building:
![image](https://github.com/Yirmiri/Excessive-Building/assets/4038592/2471888f-746e-4c29-bad2-f81ea5a23413)

Oak Sapling Tag List With Excessive Building
![image](https://github.com/Yirmiri/Excessive-Building/assets/4038592/d4b5e073-b86a-41ff-9147-b81dbd206b62)

Oak Sapling Tag List Without Excessive Building (forge:sapling now the only remaining thing in the item tags list, minecraft:saplings is now gone which breaks many other mods):
![image](https://github.com/Yirmiri/Excessive-Building/assets/4038592/a7030d1e-ddb9-4251-a26c-d68a5cbf7960)

Edit: changed all references to the minecraft:saplings ITEM TAG.  It is not just the oak sapling that is broken, many other saplings including some modded saplings are broken.

**Comment by Alaric323** [comment]
Another update, it appears that specifically the golden birch sapling has no tags (even block tags).  All other saplings have block tags.

![image](https://github.com/Yirmiri/Excessive-Building/assets/4038592/46664f3d-5c07-4f84-b3f0-8afa28f3471d)

From what I understand, the issue is not "a lack of item tags", a lot of other mods do that.

**Comment by Yirmiri** [comment]
Sorry for the late response I have been finishing other things first but I will look into this when I get the chance, thank you for all the information :)

**Comment by Alaric323** [comment]
All good! Good luck with the fix!

**Comment by Alaric323** [comment]
I can confirm the latest build (2.2) fixed the issue!  Great work!
