### ISSUE TITLE
Craftingtable variants not working

### ISSUE THREAD

**Issue by ThatFinn** [Yirmiri/Excessive-Building-Forge#14]
I am using version 1.4.3-1.20.2.
If I open a non vanilla crafting table, I can see the UI for a split second before it disappears again, making it unsable. I've tried using just this mod (to rule out other mods as culprits), but the problem still persists.

**Comment by Yirmiri** [comment]
I cannot replicate this issue and sadly 1.20.2 is currently not actively supported.
I'd recommend playing with an older version as a replacement.
