### ISSUE TITLE
Missing biome language entries, and more tags needed

### ISSUE THREAD

**Issue by Mechalopa** [Yirmiri/Excessive-Building-Forge#15]
![screenshot](https://github.com/Yirmiri/Excessive-Building/assets/92443696/ce3be579-f1d8-4988-afb3-28b86ce27219)
(Example screenshot using nature's compass mod)
Additional biomes do not have valid language entries.

Also, additional biome is not contained in `minecraft:is_overworld` biome tag.
And I think snowy maple forest needs to be contained in `forge:is_cold/overworld` and `forge:is_snowy` biome tags.

Note: forge version.

**Comment by Yirmiri** [comment]
Will be included with version 3.0.0!
