### ISSUE TITLE
java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/ParticleEngine for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Mikeatron-User** [Yirmiri/Excessive-Building-Forge#5]
Minecraft Version: `1.20.1`
Forge Version: `47.2.0`
Mod Version: `1.20.1-2.0.2`
Log: https://mclo.gs/mWE0lXX

Trying to load up a server with the excessive building mod. Instant crash.

**Comment by evertn** [comment]
Same here.

Went back to 1.20.1-2.0.0. That version is working on a server.

**Comment by Yirmiri** [comment]
I have fixed the issue in the soon to be latest build, V2.0.3.
Thank you for bringing this to my attention :)

- edit, Version 2.0.3 is now out
