### ISSUE TITLE
Ancient Sapling not spawning from Sniffers (1.20.1 Fabric)

### ISSUE THREAD

**Issue by ServerSizeMe** [Yirmiri/Excessive-Building-Forge#7]
Title describes it, 
I've been trying to test out drop chances with a mass of Sniffers from a spawner but so far I've gotten nothing after about 100 rolls.
Unsure if just unlucky though.

**Comment by ServerSizeMe** [comment]
the loot table modifier text file mentions Forge:loot_table_id rather than fabric,

**Comment by Yirmiri** [comment]
Thanks, a fix will be available in the next release of Fabric 1.20.1
