### ISSUE TITLE
(Bug) Latest 2 versions have broken the sapling tag

### ISSUE THREAD

**Issue by Devilswarchild** [Yirmiri/Excessive-Building-Forge#9]
mc version: 1.20.1
Forge Version: 47.2.20

Excessive Building versions 2.1.3 and 2.1.4 both have an issue where anything requiring saplings for crafting will not craft. ended up having to downgrade to 2.1.2 in order to get it working again.

versions 2.1.3 - 2.1.4
![Screenshot_2](https://github.com/Yirmiri/Excessive-Building/assets/27385258/9d00c165-7e56-4469-8fb6-26faa2293d02)

this is what should be happening 
![image](https://github.com/Yirmiri/Excessive-Building/assets/27385258/0f130d77-0c5c-43f3-ac82-0b3ec76dc079)

[debug.log](https://mclo.gs/jXrHwPv)

[latest.log](https://mclo.gs/ao4e6Mg)

**Comment by Yirmiri** [comment]
Thank you I have released a version to solve this issue, It will take time to be reviewed on CurseForge.

**Comment by Devilswarchild** [comment]
> Thank you I have released a version to solve this issue, It will take time to be reviewed on CurseForge.

You are very welcome
